const Question = [
    {
        id: 1,
        question: "What is the virtual DOM?",
        answer: "DOM stands for Document Object Model. The DOM represents the HTML structure in a tree-like format. The virtual DOM is an in-memory representation of the real DOM elements generated by React components before any changes are made to the web page. It allows React to perform efficient updates by only changing the elements that need to be changed."
    },
    {
        id: 2,
        question: "What is React?",
        answer: "React is a JavaScript library for building user interfaces. It allows developers to create large web applications that can change data, without reloading the page. Its main goal is to be fast, simple, and scalable."
    },
    {
        id: 3,
        question: "What are props in React?",
        answer: "Props (short for properties) are a way of passing data from parent to child components in React. They are read-only and cannot be modified by the child component."
    },
    {
        id: 4,
        question: "What is state in React?",
        answer: "State is a built-in object in React that is used to store property values that belong to a component. When the state object changes, the component re-renders."
    },
    {
        id: 5,
        question: "What is a component in React?",
        answer: "A component in React is a reusable piece of code that can accept inputs (props) and returns a React element that describes how a section of the UI should appear."
    },
    {
        id: 6,
        question: "What is JSX?",
        answer: "JSX stands for JavaScript XML. It is a syntax extension for JavaScript that looks similar to HTML. It is used with React to describe what the UI should look like."
    },
{
        id: 7,
        question: "What is a higher-order component (HOC) in React?",
        answer: "A higher-order component (HOC) is a function that takes a component and returns a new component. HOCs are used for reusing component logic."
    },
    {
        id: 8,
        question: "What are hooks in React?",
        answer: "Hooks are functions that let you use state and other React features without writing a class. The most commonly used hooks are useState and useEffect."
    },
    {
        id: 9,
        question: "What is Redux?",
        answer: "Redux is a predictable state container for JavaScript apps. It helps you write applications that behave consistently, run in different environments, and are easy to test."
    },
    {
        id: 10,
        question: "What is the difference between state and props in React?",
        answer: "State is a local data storage that is local to the component only and cannot be passed to other components. Props are used to pass data from one component to another."
    }
];

export default Question;